# Generated by Django 5.0.14 on 2026-04-24 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATKCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori ATK',
                'verbose_name_plural': 'Kategori ATK',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ATKItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama ATK')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('pack', 'Pack'), ('rim', 'Rim'), ('roll', 'Roll'), ('bottle', 'Botol'), ('tube', 'Tube'), ('set', 'Set')], default='pcs', max_length=20, verbose_name='Satuan')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('minimum_stock', models.IntegerField(default=10, verbose_name='Stok Minimum')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Harga per Satuan')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Supplier')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokasi Penyimpanan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='atk.atkcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Item ATK',
                'verbose_name_plural': 'Item ATK',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ATKRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Jumlah')),
                ('reason', models.TextField(verbose_name='Alasan/Keperluan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('completed', 'Selesai')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Disetujui')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_atk_requests', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='atk.atkitem', verbose_name='Item ATK')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atk_requests', to=settings.AUTH_USER_MODEL, verbose_name='Peminta')),
            ],
            options={
                'verbose_name': 'Permintaan ATK',
                'verbose_name_plural': 'Permintaan ATK',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATKTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar'), ('adjustment', 'Penyesuaian')], max_length=20, verbose_name='Jenis Transaksi')),
                ('quantity', models.IntegerField(verbose_name='Jumlah')),
                ('description', models.TextField(verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='atk.atkitem', verbose_name='Item ATK')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atk.atkrequest', verbose_name='Terkait Permintaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaksi ATK',
                'verbose_name_plural': 'Transaksi ATK',
                'ordering': ['-created_at'],
            },
        ),
    ]
