# Generated by Django 5.0.14 on 2026-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktransaction',
            name='request',
        ),
        migrations.RemoveField(
            model_name='atktransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='atktransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='atkitem',
            name='location',
        ),
        migrations.AddField(
            model_name='atkitem',
            name='recipient',
            field=models.CharField(blank=True, max_length=200, verbose_name='Penerima'),
        ),
        migrations.DeleteModel(
            name='ATKRequest',
        ),
        migrations.DeleteModel(
            name='ATKTransaction',
        ),
    ]
