# Generated by Codex on 2026-05-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0002_remove_atktransaction_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATKRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Item Lainnya')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('purpose', models.TextField(verbose_name='Keperluan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Catatan Admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pengajuan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='atk.atkitem', verbose_name='Item ATK')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atk_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pemohon')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_atk_requests', to=settings.AUTH_USER_MODEL, verbose_name='Direview Oleh')),
            ],
            options={
                'verbose_name': 'Pengajuan ATK',
                'verbose_name_plural': 'Pengajuan ATK',
                'ordering': ['-created_at'],
            },
        ),
    ]
