# Generated by Codex on 2026-05-26

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_request_lines(apps, schema_editor):
    ATKRequest = apps.get_model('atk', 'ATKRequest')
    ATKRequestLine = apps.get_model('atk', 'ATKRequestLine')

    lines = []
    for request in ATKRequest.objects.all():
        if request.item_id or request.custom_item_name:
            lines.append(ATKRequestLine(
                request_id=request.id,
                item_id=request.item_id,
                custom_item_name=request.custom_item_name,
                quantity=request.quantity,
            ))

    ATKRequestLine.objects.bulk_create(lines)


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0003_atkrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATKRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Item Lainnya')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_lines', to='atk.atkitem', verbose_name='Item ATK')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='atk.atkrequest', verbose_name='Pengajuan')),
            ],
            options={
                'verbose_name': 'Item Pengajuan ATK',
                'verbose_name_plural': 'Item Pengajuan ATK',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copy_legacy_request_lines, migrations.RunPython.noop),
    ]
