# Generated by Django 5.0.14 on 2026-06-08 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0004_atkrequestline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atkcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='atkcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='atkitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='atkitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama ATK'),
        ),
        migrations.AlterField(
            model_name='atkrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tanggal Pengajuan'),
        ),
        migrations.AlterField(
            model_name='atkrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='atkitem',
            index=models.Index(fields=['category', 'name'], name='atk_item_category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='atkrequest',
            index=models.Index(fields=['requester', 'status', '-created_at'], name='atk_req_requester_status_idx'),
        ),
        migrations.AddIndex(
            model_name='atkrequest',
            index=models.Index(fields=['status', '-created_at'], name='atk_req_status_created_idx'),
        ),
    ]
