# Generated by Django 5.0.14 on 2026-06-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0005_alter_atkcategory_created_at_alter_atkcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atkrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('needs_purchase', 'Perlu Pembelian'), ('rejected', 'Ditolak')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
