# Generated by Django 5.0.14 on 2026-06-10 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0006_alter_atkrequest_status'),
        ('users', '0005_division_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATKDivisionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stok Divisi')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Minimum Divisi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atk_stocks', to='users.division', verbose_name='Divisi')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_stocks', to='atk.atkitem', verbose_name='Item ATK')),
            ],
            options={
                'verbose_name': 'Stok ATK Divisi',
                'verbose_name_plural': 'Stok ATK Divisi',
                'ordering': ['division__name', 'item__name'],
                'indexes': [models.Index(fields=['division', 'item'], name='atk_div_stock_div_item_idx')],
                'unique_together': {('item', 'division')},
            },
        ),
    ]
