# Generated by Django 5.0.14 on 2026-06-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atk', '0008_backfill_division_stock'),
        ('users', '0007_normalize_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='atkrequest',
            name='stock_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stok Diterapkan Pada'),
        ),
        migrations.AddField(
            model_name='atkrequest',
            name='stock_applied_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_atk_requests', to='users.division', verbose_name='Stok Diterapkan ke Divisi'),
        ),
    ]
