# Generated by Django 5.0.14 on 2026-03-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='NIK/ID Karyawan')),
                ('primary_email', models.EmailField(max_length=254, unique=True, verbose_name='Email Utama')),
                ('email_password', models.CharField(max_length=255, verbose_name='Password Email')),
                ('recovery_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Recovery')),
                ('recovery_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='No HP Recovery')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Karyawan',
                'verbose_name_plural': 'Email Karyawan',
                'ordering': ['-created_at'],
            },
        ),
    ]
