# Generated by Django 5.0.14 on 2026-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeemail',
            name='primary_email',
            field=models.TextField(verbose_name='Email Utama'),
        ),
    ]
