# Generated by Django 5.0.14 on 2026-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employeeemail_primary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='employeeemail',
            name='email_password',
            field=models.TextField(verbose_name='Password Email'),
        ),
        migrations.AlterField(
            model_name='employeeemail',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Status Aktif'),
        ),
        migrations.AddIndex(
            model_name='employeeemail',
            index=models.Index(fields=['is_active', '-created_at'], name='email_active_created_idx'),
        ),
    ]
