# Generated by Django 5.0.14 on 2026-03-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Tiket')),
                ('description', models.TextField(verbose_name='Deskripsi Masalah')),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('urgent', 'Darurat')], default='medium', max_length=20, verbose_name='Prioritas')),
                ('status', models.CharField(choices=[('new', 'Baru'), ('in_progress', 'Diproses'), ('completed', 'Selesai'), ('rejected', 'Ditolak')], default='new', max_length=20, verbose_name='Status')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='Lampiran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='inventory.equipment', verbose_name='Barang Terkait')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor')),
            ],
            options={
                'verbose_name': 'Tiket',
                'verbose_name_plural': 'Tiket',
                'ordering': ['-created_at'],
            },
        ),
    ]
