# Generated by Django 5.0.14 on 2026-03-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan saat tiket selesai atau tidak selesai', verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Baru'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Tidak Selesai')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
