# Generated by Django 5.0.14 on 2026-06-08 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipment_created_at_and_more'),
        ('tickets', '0002_ticket_notes_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('urgent', 'Darurat')], db_index=True, default='medium', max_length=20, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Baru'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Tidak Selesai')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reporter', 'status', '-created_at'], name='ticket_reporter_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_status_created_idx'),
        ),
    ]
