# Generated by Django 5.0.14 on 2026-06-08 04:05

from django.db import migrations, models


def populate_ticket_codes(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.order_by('id'):
        if not ticket.ticket_code:
            ticket.ticket_code = f"APM/TCT/{ticket.id:03d}"
            ticket.save(update_fields=['ticket_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_created_at_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='ID Tiket'),
        ),
        migrations.RunPython(populate_ticket_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='ID Tiket'),
        ),
    ]
