# Generated by Django 5.0.14 on 2026-06-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimated_completion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Selesai'),
        ),
    ]
