# Generated by Django 5.0.14 on 2026-03-04 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori Peralatan',
                'verbose_name_plural': 'Kategori Peralatan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('inventory_code', models.CharField(max_length=100, unique=True, verbose_name='Kode Inventaris')),
                ('specifications', models.TextField(blank=True, verbose_name='Spesifikasi')),
                ('current_user', models.CharField(blank=True, max_length=200, verbose_name='Pengguna Saat Ini')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('borrowed', 'Dipinjam'), ('broken', 'Rusak'), ('service', 'Servis')], default='available', max_length=20, verbose_name='Status')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Pembelian')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Garansi Sampai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.equipmentcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Peralatan',
                'verbose_name_plural': 'Peralatan',
                'ordering': ['-created_at'],
            },
        ),
    ]
