# Generated by Django 5.0.14 on 2026-04-07 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.equipmentcategory', verbose_name='Kategori Induk'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Kategori'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcategory',
            unique_together={('name', 'parent')},
        ),
    ]
