# Generated by Django 5.0.14 on 2026-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipmentcategory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lokasi/Tempat'),
        ),
    ]
