# Generated by Django 5.0.14 on 2026-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Kode Inventaris'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nama Barang'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('borrowed', 'Dipinjam'), ('broken', 'Rusak'), ('service', 'Servis')], db_index=True, default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nama Kategori'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'status'], name='equip_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', '-created_at'], name='equip_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcategory',
            index=models.Index(fields=['parent', 'name'], name='equip_cat_parent_name_idx'),
        ),
    ]
