# Generated by Django 5.0.14 on 2026-06-10 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('inventory_code', models.CharField(db_index=True, max_length=100, verbose_name='Kode Inventaris')),
                ('category_name', models.CharField(max_length=200, verbose_name='Kategori')),
                ('status', models.CharField(max_length=50, verbose_name='Status Terakhir')),
                ('current_user', models.CharField(blank=True, max_length=200, verbose_name='Pengguna Terakhir')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokasi Terakhir')),
                ('reason', models.TextField(verbose_name='Alasan Penghapusan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inventory/deletion-logs/', verbose_name='Lampiran Penghapusan')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tanggal Penghapusan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_deletion_logs', to=settings.AUTH_USER_MODEL, verbose_name='Dihapus Oleh')),
            ],
            options={
                'verbose_name': 'Log Penghapusan Aset',
                'verbose_name_plural': 'Log Penghapusan Aset',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
