# Generated by Django 5.0.14 on 2026-03-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pengecekan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dicek Oleh')),
            ],
            options={
                'verbose_name': 'Log Pengecekan Jaringan',
                'verbose_name_plural': 'Log Pengecekan Jaringan',
                'ordering': ['-checked_at'],
            },
        ),
    ]
