# Generated by Django 5.0.14 on 2026-06-08 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkchecklog',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Waktu Pengecekan'),
        ),
        migrations.AddIndex(
            model_name='networkchecklog',
            index=models.Index(fields=['checked_by', '-checked_at'], name='network_user_checked_idx'),
        ),
    ]
